### ISSUE TITLE
Latest compatible/tested OPNSense

### ISSUE THREAD

**Issue by rvalle** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense#17]
Hi!

I need to upgrade my firewall... but again, up to which version?

Would be nice to have the latest version of OPNSense this version is compatible with somwhere:

Perhaps in the Readme.md?
Perhaps in Release/Change logs?

What is the last tested opnsense version compatible with this playbook?

**Comment by zerwes** [comment]
would be something related to #15 having a list of supported versions running some tests against ...
The latest version my testnode(s) are currently on is **_22.1.9_**
I'll monitor the up-to-date status using [firmware_status.py](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-checkmk/blob/main/files/firmware_status.py) and [pkg_audit.py](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-checkmk/blob/main/files/pkg_audit.py) and try to keep them updated using [ansible-opnsense-update](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update)
But this node(s) are rather a playground then some heavy tested prod systems (the target to be this later, but the rise of the day called 'later' is not part of my workflow for now)

**Comment by zerwes** [comment]
As for example #23 is in fact a version related fix (sorting was IMHO introduced somewhere in 21.X), this should become more important to list the latest supported versions ...
I think something like this should be reasonable:
 * community:
   * old-stable : currently 22.1
   * stable: currently 22.7
 * business:
   * old-stable: currently 22.4
   * stable: 22.10

Later some automated tests including the next release candidates would be a giant step.

Links:
 * https://docs.opnsense.org/releases.html
 * https://opnsense.org/about/road-map/
 * https://www.versio.io/product-release-end-of-life-eol-OPNsense-OPNsense.html

**Comment by zerwes** [comment]
just for the record ... currently using the role on
 * 22.10.2
 * 23.1.5_4

**Comment by zerwes** [comment]
just for the record ... currently using the role on
 * 22.10.2
 * 23.1.6

**Comment by zerwes** [comment]
current state:
  * 23.4 (BE)
  * 23.7

**Comment by rvalle** [comment]
I am testing on OPNsense 23.7.10_1-amd64, but I am not sure unbound is working, I will review before putting an issue...

**Comment by zerwes** [comment]
> I am testing on OPNsense 23.7.10_1-amd64, but I am not sure unbound is working, I will review before putting an issue...

I setup a opnsense based project using unbound for some colleagues RLS; I myself do not use unbound on opnsense, I prefer a standalone setup.
But I realized some major changes in the opnsense cfg around the release of ~ 22.7.6 / business edition 23.10 ... most of the cfg stuff has been migrated from unbound to unboundplus settings ... and at some point the old unbound tag disappeared.
I opened a internal issue for this topic for my colleagues more then a year ago, but I see no progress there :-1: 
So I assume you are right. So please collect the required information and open a issue here, maybe this will increase the pressure ...

**Comment by rvalle** [comment]
@zerwes yes, that I noticed, that the ansible roles where setting configurations under unbound and the config file was populated under unboundplus, thou they seem to be the same kind of records.

I use it for two specific use cases: registering DHCP reservations as DNS entries and DNS overrides (hosts and domains). I think this can only be done with unbound, or?

**Comment by zerwes** [comment]
I use the *register DHCP leases* feature with unbound (on a node where unbound was configured via ansible long before the changes discussed before), but I think dnsmasq supports this too ... but I am no expert on this topic, the opnsense forum might be the better place for information on that ...

**Comment by zerwes** [comment]
as we use both versions (BE and community) we try to keep the role compatible with the latest versions ... best effort principle
