### ISSUE TITLE
forking naturalis repo

### ISSUE THREAD

**Issue by rvalle** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense#2]
As discussed on https://github.com/naturalis/ansible-opnsense/issues/38
Can you contact me by email and we discuss further? 
You can find my details in the contributor list.

**Comment by rvalle** [comment]
I have reached to OPNSense core team with regards to coordinating efforts on the Ansible Modules, we are speaking next week. Would you like to come?

**Comment by zerwes** [comment]
Ough ... sorry, I missed this. My answer is in naturalis#38

**Comment by zerwes** [comment]
it is like it is ...

 * we have the RLS fork wit somehow vital development on it ...
 * naturalis is not merging PRs, so the state of the repos is quite diverged ... and to be honest: I stopped opening PRs in the original repo.
 * opnsense core team has no interest in ansible support (somehow understandable from their point of view)
 * I have no spare resources to start a rewrite switching from the dull xml manipulation to real interaction with the target device using the API

So for now I am closing this.
